# 应用服务 WEB 访问端口
server:
  port: 8082
# 应用名称
spring:
  application: name=from-zero-to-expert
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myproject?serverTimezone=GMT%2B8
    username: "root"
    password: "0612"
#自定义属性 读取值
project:
    nickname: "JJLin's project, from-zero-to-expert"
    index:
      cookie:
        name: "name"
        value: "JJLin"
      redirectPath: "/accessIndexAgain"

#是否启用swagger2
swagger:
  enable: true

#RSA 的密钥长度
#RSA:
#  modules: 512